### ISSUE TITLE
Include info on which speaker expenses are covered

### ISSUE THREAD

**Issue by brzpegasus** [WickedGoodConferences/ember#147]
Not sure where this can go on the website (FAQ?), but it would be good to post information on what will be covered for speakers (i.e. conf ticket + 2-night lodging), and when/how speakers can expect to get reimbursed (after final speaker list is determined).

/cc @acacheung

**Comment by acacheung** [comment]
@bcardarella ^

**Comment by bcardarella** [comment]
Go for it

**Comment by Ctannerweb** [comment]
Copy for this years FAQ section is being looked over by Chris and Tim. Will coordinate with them to get this included 👍

**Comment by walshtim** [comment]
@bcardarella @Ctannerweb Can the information about what the speaker receives be shown on the form for applying? https://docs.google.com/forms/d/1dWJKc3244owUjxvj9QyA2cn3VHFdaHr37OQeWJdt-aw/viewform 

Also currently we don't have an FAQ on the site. Is this something we would like to add & can we use copy from last years?

**Comment by Ctannerweb** [comment]
@bcardarella Wanted to bring this issue up again. if we are going to add a FAQ might as well do it when we add speakers to the site also 👍

**Comment by acacheung** [comment]
Closing because we never got copy for this
