### ISSUE TITLE
UXD: Add schedule page

### ISSUE THREAD

**Issue by Ctannerweb** [WickedGoodConferences/ember#153]

**Comment by bcardarella** [comment]
https://docs.google.com/spreadsheets/d/1O4_ibSWe0gkumSMh3-yTE7oE8u_A2sA80c8N7lHMkkM/edit?usp=sharing

Final schedule. Some of the boat times may change but the structure is roughly final

**Comment by walshtim** [comment]
@bcardarella Should I be using the content from this doc to mock up the printed version of the schedule? If so, do we only want to show events from Monday and Tuesday?

**Comment by bcardarella** [comment]
@walshtim this is the finalized schedule and should be reflected in full on the site

**Comment by walshtim** [comment]
@bcardarella Yeah, having the full schedule on the site makes sense. But for the printed version (the poster sized ones that will be in the conference hall) we talked about only showing the days when talks will be occurring. Thoughts?

**Comment by bcardarella** [comment]
@walshtim I see, yes only Monday & Tuesday for printed material

**Comment by bcardarella** [comment]
@acacheung what's the status on this?

**Comment by acacheung** [comment]
waiting on design ok. will assign you pr when ready
