### ISSUE TITLE
Add Ruby on Sails

### ISSUE THREAD

**Issue by bcardarella** [WickedGoodConferences/ember#157]
Company URL
http://www.rubyonsails.net
Company Twitter
@rubyonsails
Company Logo URL
https://www.dropbox.com/s/xq4z8kiuealyzhz/ros_logo.svg?dl=0
Do you have any special requests you'd like to let the organizers know?
Unanswered

The website doesn't work, I have no idea what is going on. But that is the info they provided

**Comment by acacheung** [comment]
@bcardarella what level?

**Comment by acacheung** [comment]
I'll link to this instead: http://rubyonsails.info/

**Comment by bcardarella** [comment]
"Good" sponsor. Other URL is OK
