### ISSUE TITLE
Add speakers

### ISSUE THREAD

**Issue by bcardarella** [WickedGoodConferences/ember#158]
- [x] Gaurav Munjal - Test Driven Development in Ember Twiddle
- [x] Katie Gengler - The devil is in the details -- Building an Ember addon the right way
- [x] Philip Poots - Elmber
- [x] Mike North - Delightful UX for Distributed Systems
- [x] Liz Baillie - Journey to the cneter of Ember Test Helpers
- [x] Trent Willis - Maintaining your tests at scale

**Comment by acacheung** [comment]
Fixed via #165, #164, #162 and #160
