### ISSUE TITLE
moar speakers

### ISSUE THREAD

**Issue by bcardarella** [WickedGoodConferences/ember#167]
- [x] Iheanyi Ekechukwu
- [x] Erik Bryn (his talk is TBD)
- [x] Kelly Senna
- [x] Chris Thoburn

**Comment by acacheung** [comment]
@bcardarella which talk for Chris Thoburn?

**Comment by bcardarella** [comment]
Beyond 60fps

**Comment by bcardarella** [comment]
Erik is going to do the CSS one. He wants to call it "Taming CSS in Ember.js Apps"
