### ISSUE TITLE
Add mini-workshop

### ISSUE THREAD

**Issue by acacheung** [WickedGoodConferences/ember#180]
- [x] @bcardarella to provide copy 
- [ ] Discuss design with Chris/Tim
- [ ] Implement additions

**Comment by bcardarella** [comment]
I just shared a Google Doc with you that has the workshop info


----------------------
Brian Cardarella
CEO of DockYard
Visit us: http://dockyard.com
Call us: (855) DOCK-YRD
Follow me on Twitter: http://twitter.com/bcardarella
Follow us on Twitter: http://twitter.com/DockYard
