### ISSUE TITLE
formatting issues with updated copy on ac-wge2015 branch

### ISSUE THREAD

**Issue by bcardarella** [WickedGoodConferences/ember#34]
![screen_shot_2015-03-01_at_1_31_29_pm](https://cloud.githubusercontent.com/assets/18524/6432964/1795b5d4-c018-11e4-8ffb-61831f12ebf0.png)
![screen_shot_2015-03-01_at_1_31_49_pm](https://cloud.githubusercontent.com/assets/18524/6432965/17bf9610-c018-11e4-80b9-ae06f03bff6d.png)
![screen_shot_2015-03-01_at_1_31_56_pm](https://cloud.githubusercontent.com/assets/18524/6432966/17cae010-c018-11e4-8170-bbdf9487c988.png)

**Comment by bcardarella** [comment]
ping @acacheung

**Comment by acacheung** [comment]
Separated this issue out into smaller issues
