### ISSUE TITLE
Fix Sponsor Logos

### ISSUE THREAD

**Issue by walshtim** [WickedGoodConferences/ember#92]
Orient sponsor logos so that companies who donated more money are larger.

**Comment by acacheung** [comment]
![screen shot 2015-05-06 at 6 04 28 pm](https://cloud.githubusercontent.com/assets/1054686/7504718/5fd09f04-f41a-11e4-9ed4-2690d70efc61.png)

**Comment by acacheung** [comment]
@bcardarella Clicking on the "Be the video sponsor" should bring up the Sponsor google form (https://docs.google.com/forms/d/1OSZvL5igYQHHsoRtO3DlksXeZ-kdYQ7HpfdwsCBINt0/viewform) but there is no choice to become the video sponsor when you choose your sponsor level. Is this okay? They could just select Very Good and note that it's for video?

**Comment by bcardarella** [comment]
@acacheung fixed

**Comment by bcardarella** [comment]
@acacheung :+1: on this layout
