### ISSUE TITLE
Adding Schedule to WGE site

### ISSUE THREAD

**Issue by walshtim** [WickedGoodConferences/ember#93]
Hi @bcardarella - I just wanted to get some more details about what you had in mind for the schedule. If you could provide breakdown of how the day should be scheduled (i.e. breakfast, introductions, talk, lunch, talk, etc.) that would be great. 

Also are we still planning on doing bios for each speaker? If so, I can create a new issue for it. 

Thanks!

**Comment by walshtim** [comment]
@bcardarella - Also here are the jpgs of the sketches that I emailed out a couple of weeks ago (it's probably easier to keep it all in one place). Again, I think I'm leaning with something like the last one which orients each time slot vertically and allows for the content to sit more comfortably when compared to horizontal orientation.  

![2_schedule](https://cloud.githubusercontent.com/assets/6773193/7475020/25c7725e-f313-11e4-9118-aeef26f4991c.jpg)
![3_schedule](https://cloud.githubusercontent.com/assets/6773193/7475018/25c52b48-f313-11e4-870b-fa8d5a9060b8.jpg)
![4_schedule](https://cloud.githubusercontent.com/assets/6773193/7475019/25c5c22e-f313-11e4-8fd7-897fbb0b3598.jpg)

**Comment by walshtim** [comment]
Hi @bcardarella - I just wanted to post some mock-ups of the WGE schedule that I've been working on. 
Also just to note, because this page is getting pretty lengthy, I added in a fixed navigation (Nav.jpg) to help indicate where the user is during the experience. 

![nav](https://cloud.githubusercontent.com/assets/6773193/7504413/fa7c2670-f417-11e4-8b8f-e5b41d5196c9.jpg)


**_0000_Schedule hover.jpg** - This jpg shows the schedule with no descriptions expanded and a hover state on the talk title. Clicking on the title expands both the description and a link to the speakers bio (the same action can be taken in the speaker section).

![_0000_schedule hover](https://cloud.githubusercontent.com/assets/6773193/7504448/363af056-f418-11e4-8bcf-da455c944456.jpg)

**_0001_Talk expanded** - Shows an example of how one description expanded would look. Also an 'X' to close appears in the corner of the description. 

![_0001_talk expanded](https://cloud.githubusercontent.com/assets/6773193/7504450/39363658-f418-11e4-9bd3-795f556fad78.jpg)

**_0002_All expanded.jpg** - Shows all descriptions expanded. Also, below the section title, there's a link to close all open descriptions. I put this in to so the user can avoid having to scroll through a lot of 
text. Also on some of the items I put a cross-hatched pattern. I was thinking this could be used to indicate the general group activities. Was also thinking this could serve as a way to indicate what's happening now. 

![_0002_all expanded](https://cloud.githubusercontent.com/assets/6773193/7504453/3d7c963a-f418-11e4-848f-c91b42152ece.jpg)

**Also here is the page with schedule for context:**

![full](https://cloud.githubusercontent.com/assets/6773193/7504462/5485bb5e-f418-11e4-8332-ed80ee49de97.jpg)


Let me know your thoughts on this, thanks!

**Comment by bcardarella** [comment]
Getting there. I'd rather be able to click on individual calendar items to expand/collapse rather than an Expand/Collapse All.

We also need a way to incorporate speaker bios into the single page.

**Comment by walshtim** [comment]
@bcardarella - If you look at the third jpg down, named **_0001_Talk expanded** you can see an example of what it looks like to just have one expanded. The idea being that they could click on the title of the talk to see the description or click the link to expand them all.

Also I have a couple sketches for how the speaker bios could work. I’ll just create another issue and post them there.

**Comment by walshtim** [comment]
@bcardarella - Here is the mobile version of the schedule.

![schedule_1a](https://cloud.githubusercontent.com/assets/6773193/7539755/1af93a7c-f577-11e4-8acd-1f0df1e5fbdc.jpg)
