### ISSUE TITLE
Adding speaker bios to WGE site

### ISSUE THREAD

**Issue by walshtim** [WickedGoodConferences/ember#98]
@bcardarella - The idea here is that once the user has clicked 'Full Bio' an overlay would appear revealing the speaker’s picture, social media links, their biography, arrows to toggle between other speakers, and maybe a link to the schedule where they can see the time of their talk (for this, I imagine it would just close the overlay and bring you to the schedule with that person's talk description already expanded).

![1_speakers bio](https://cloud.githubusercontent.com/assets/6773193/7517854/72616528-f4a5-11e4-867a-b3182318d571.jpg)

**Comment by bcardarella** [comment]
I know I wanted to do this but I don't think we'll have time to implement. Let's simplify this

**Comment by walshtim** [comment]
@bcardarella - Here is the design for the speaker bios. It probably makes sense to order them according to the order they will be speaking in. Also like the schedule, clicking on the talk title will bring you back to the schedule with that description expanded. 

I will also begin working on a mobile version of both this and the schedule. 

![speaker_1a](https://cloud.githubusercontent.com/assets/6773193/7525800/78940858-f4da-11e4-972e-859cd7e73211.jpg)

**Comment by walshtim** [comment]
@bcardarella - Here's the mobile version of the speaker bios. 

![speaker_1a](https://cloud.githubusercontent.com/assets/6773193/7541512/07cc7df8-f584-11e4-9bde-19cb95556a80.jpg)

**Comment by bcardarella** [comment]
Looks great!
